server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 2MB

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
user:
  httpImage : http://image.leyou.com/