server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///leyou?serverTimezone=CST&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 192.168.58.132

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.leyou.dao.*: debug #打印sql语句

mybatis:
  type-aliases-package: com.leyou.user.pojo  #    实体类别名
  mapper-locations: classpath:mappers/*.xml #  扫描 mapper.xml文件
  configuration:
    map-underscore-to-camel-case: true
